version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: bukis_postgres
    environment:
      POSTGRES_DB: bukis_development
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
