default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5433
  user: admin
  password: admin
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: bukis_development